[package]
name = "rtweekend"
version = "0.1.0"
edition = "2021"

[dependencies]
impl_ops = "^0.1.1"
rand = "^0.8.5"
num = "^0.4.0"
threadpool = "^1.8.1"
clap = { version = "^4.0.14", features = ["derive"] }
